# Generated by Django 3.1.6 on 2021-02-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mililitros', models.IntegerField()),
                ('artesanal', models.BooleanField()),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
            ],
        ),
    ]
